version: 2
snapshot:
  enable-javascript: true
  widths: [768]
discovery:
  allowed-hostnames: 
  - localhost:3001
  - localhost:3000
  launch-options:
    executable: '/usr/bin/chromium-browser'
    headless: false
    args: 
    - '--disable-gpu'
    - '--disable-dev-shm-usage'
    - '--disable-setuid-sandbox'
    - '--no-sandbox'
